const scenarios={
 nominal:{label:'Nominal',severity:'ok',values:{flow:72,current:68,speed:76,vision:84,vibration:34},diag:'ALIMENTATION STABLE',conf:94,evidence:['Débit et courant évoluent de manière cohérente.','Pas de rupture CUSUM persistante sur la fenêtre récente.','Indice visuel compatible avec un flux continu et réparti.'],rec:'Poursuivre la surveillance. Aucune action opérateur requise.'},
 bridging:{label:'Pontage / blocage',severity:'high',values:{flow:28,current:74,speed:72,vision:31,vibration:61},diag:'PONTAGE PROBABLE',conf:91,evidence:['Débit en forte baisse malgré un entraînement toujours chargé.','Rupture CUSUM détectée sur la variable de débit.','La scène visuelle indique une zone de matière immobile / alimentation discontinue.'],rec:'Vérifier la trémie et la zone de transfert. Confirmer mécaniquement avant toute intervention.'},
 starvation:{label:'Sous-alimentation',severity:'warn',values:{flow:24,current:35,speed:77,vision:43,vibration:29},diag:'SOUS-ALIMENTATION',conf:89,evidence:['Courant moteur et débit chutent simultanément.','Vitesse disponible mais charge mécanique faible.','Tendance Theil–Sen négative du débit sur plusieurs fenêtres.'],rec:'Contrôler disponibilité matière en amont et consigne de dosage. Ne pas compenser automatiquement.'},
 slippage:{label:'Glissement',severity:'warn',values:{flow:41,current:77,speed:49,vision:67,vibration:72},diag:'GLISSEMENT / TRANSMISSION',conf:87,evidence:['Charge électrique élevée avec vitesse effective en baisse.','Décorrélation vitesse–débit et hausse de vibration.','Énergie spectrale accrue sur la bande mécanique surveillée.'],rec:'Demander une vérification entraînement/transmission et comparer la vitesse commandée à la vitesse mesurée.'},
 camera_degraded:{label:'Caméra dégradée',severity:'ood',values:{flow:63,current:65,speed:72,vision:8,vibration:38},diag:'ABSTENTION — HORS DOMAINE',conf:37,evidence:['Qualité visuelle insuffisante pour une fusion fiable.','Le moteur refuse de surinterpréter les seules variables procédé.','Les signaux non visuels restent consultables mais ne suffisent pas à conclure.'],rec:'Nettoyer / repositionner la caméra ou basculer temporairement en diagnostic procédé seul avec confiance réduite.'}
};
const labels={flow:'Débit AFR',current:'Courant moteur',speed:'Vitesse entraînement',vision:'Qualité / confiance vision',vibration:'Indice vibration'};
let current='nominal';
function sevClass(s){return s==='ok'?'sev-ok':s==='high'?'sev-high':s==='ood'?'sev-ood':'sev-warn'}
function renderButtons(){const box=document.getElementById('scenarioButtons');box.innerHTML='';Object.entries(scenarios).forEach(([k,s])=>{const b=document.createElement('button');b.textContent=s.label;b.className=k===current?'active':'';b.onclick=()=>{current=k;render()};box.appendChild(b)})}
function render(){const s=scenarios[current];renderButtons();const stream=document.getElementById('stream');stream.innerHTML='';Object.entries(s.values).forEach(([k,v])=>{const u=k==='flow'?'t/h':k==='current'?'% In':k==='speed'?'% nominal':'/100';stream.insertAdjacentHTML('beforeend',`<div class="metric"><div class="row"><span>${labels[k]}</span><b>${v}<small> ${u}</small></b></div><div class="bar"><i style="width:${Math.max(4,v)}%"></i></div></div>`)});
 document.getElementById('diagnosis').innerHTML=`<div class="severity ${sevClass(s.severity)}">${s.severity==='ok'?'ÉTAT NOMINAL':s.severity==='high'?'PRIORITÉ ÉLEVÉE':s.severity==='ood'?'ABSTENTION':'À VÉRIFIER'}</div><div class="label">${s.diag}</div><p>Décision issue d'une fusion démonstrative de cohérence procédé, signature électrique et indice visuel.</p>`;
 document.getElementById('confidencePill').textContent=`Confiance ${s.conf}%`;document.getElementById('evidenceList').innerHTML=s.evidence.map(x=>`<li>${x}</li>`).join('');document.getElementById('recommendation').innerHTML=`<b>Recommandation opérateur</b><br>${s.rec}`;
}
function tick(){document.getElementById('clock').textContent=new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}setInterval(tick,1000);tick();render();